export enum Sexo {
  MASCULINO = "MASCULINO",
  FEMININO = "FEMININO",
  OUTRO = "OUTRO",
}

export enum EstadoCivil {
  SOLTEIRO = "SOLTEIRO",
  CASADO = "CASADO",
  DIVORCIADO = "DIVORCIADO",
  VIUVO = "VIUVO",
  UNIAO_ESTAVEL = "UNIAO_ESTAVEL",
  SEPARADO = "SEPARADO",
}

export enum RegimeContratacao {
  CLT = "CLT",
  PJ = "PJ",
}

export enum GrauInstrucao {
  FUNDAMENTAL = "FUNDAMENTAL",
  MEDIO = "MEDIO",
  SUPERIOR = "SUPERIOR",
  POS_GRADUACAO = "POS_GRADUACAO",
  MESTRADO = "MESTRADO",
  DOUTORADO = "DOUTORADO",
}

export enum Escala {
  DOZE_TRINTA_SEIS = "DOZE_TRINTA_SEIS",
  SEIS_UM = "SEIS_UM",
  QUATRO_TRES = "QUATRO_TRES",
}
